/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.controller;

import io.swagger.model.Transaction;
import io.swagger.model.Transfer;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-06T19:09:28.930Z[GMT]")

@Api(value = "transfers", description = "the transfers API")
public interface TransfersApi {

    @ApiOperation(value = "get list of existing transfers", nickname = "transfersGet", notes = "all transfers", response = Transaction.class, responseContainer = "List", tags={ "transfer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Transaction.class, responseContainer = "List") })
    @RequestMapping(value = "/transfers",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Transaction>> transfersGet();


    @ApiOperation(value = "make a money transfer between accounts", nickname = "transfersPost", notes = "create new transfer. If transfer made between accounts with different currencies, then currencies convertation made according their ratio", response = Transaction.class, tags={ "transfer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Transaction.class) })
    @RequestMapping(value = "/transfers",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Transaction> transfersPost(@ApiParam(value = ""  )  @Valid @RequestBody Transfer body);


//    @ApiOperation(value = "get specified transfer", nickname = "transfersTransferIdGet", notes = "", response = Transaction.class, tags={ "transfer", })
//    @ApiResponses(value = {
//        @ApiResponse(code = 200, message = "OK", response = Transaction.class) })
//    @RequestMapping(value = "/transfers/{transferId}",
//        produces = { "application/json" },
//        method = RequestMethod.GET)
//    ResponseEntity<Transaction> transfersTransferIdGet(@ApiParam(value = "id of transfer to return",required=true) @PathVariable("transferId") Long transferId);

}
